#!/usr/bin/env node
/**
 * Apply enriched 詳解 to D1.
 *
 * Reads years/114/enrich/batch-*.json (each containing
 *   [{ id, content_json, oe_article_id, figures }] )
 * and emits a SQL file that UPDATEs explanations + inserts a
 * version+1 row into explanation_history per question.
 *
 * Usage:
 *   node scripts/apply-enrich.ts <one-batch.json> --out <out.sql>
 *   node scripts/apply-enrich.ts --all   # process every batch under enrich/
 */

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { resolve, basename } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const ENRICH_DIR = resolve(ROOT, 'years/114/enrich');

type Rec = {
  id: string;
  content_json: any;
  oe_article_id: string | null;
  figures?: { url: string; caption?: string }[];
};

async function main() {
  const args = process.argv.slice(2);
  const all = args.includes('--all');
  const outIdx = args.indexOf('--out');
  // Exclude --out and its value from the positional inputs
  const positional = args.filter((a, i) =>
    !a.startsWith('--') && i !== outIdx + 1,
  );
  const inputs: string[] = all
    ? (await readdir(ENRICH_DIR))
        .filter((f) => f.startsWith('batch-') && f.endsWith('.json'))
        .sort()
        .map((f) => resolve(ENRICH_DIR, f))
    : positional.map((a) => resolve(a));

  if (inputs.length === 0) {
    console.error('No input batch files');
    process.exit(1);
  }

  const outPath = outIdx >= 0
    ? resolve(args[outIdx + 1])
    : resolve(ROOT, 'years/114/enrich-apply.sql');

  const stmts: string[] = [
    '-- Auto-generated by scripts/apply-enrich.ts',
    '-- Bumps explanations.version by 1 per question and stores the new',
    '-- snapshot into explanation_history.',
    '-- (D1 manages its own transactions; no BEGIN/COMMIT here.)',
    '',
  ];

  let total = 0;
  for (const file of inputs) {
    const txt = await readFile(file, 'utf-8');
    const batch = JSON.parse(txt) as Rec[];
    stmts.push(`-- ${basename(file)} (${batch.length} records)`);
    for (const r of batch) {
      const json = JSON.stringify(r.content_json).replace(/'/g, "''");
      stmts.push(
        `UPDATE explanations
           SET content_json = '${json}',
               version = version + 1,
               updated_by = 'system@hema-2026',
               updated_at = strftime('%s','now')*1000
         WHERE question_id = '${r.id}';`
      );
      stmts.push(
        `INSERT INTO explanation_history (question_id, version, content_json, updated_by, updated_at)
         SELECT question_id, version, content_json, updated_by, updated_at
         FROM explanations WHERE question_id = '${r.id}';`
      );
      total++;
    }
    stmts.push('');
  }

  await writeFile(outPath, stmts.join('\n') + '\n', 'utf-8');
  console.log(`✓ Wrote ${outPath}`);
  console.log(`  ${total} explanations to update`);
  console.log(`  Apply with: wrangler d1 execute hema-2026-db --local --file=${outPath}`);
  console.log(`              wrangler d1 execute hema-2026-db --remote --file=${outPath}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
